---
title: "Writing a Research Proposal: Guidelines for prospective students at University of New England, Australia"
author: "Mick Morrison"
date: "23 October 2025"
date-modified: last-modified
date-format: "D MMMM YYYY"
format:
  html:
    theme: journal
    self-contained: true
    toc: true
    toc-depth: 3
    toc-title: "Contents"
bibliography: references.bib
csl: csl/apa.csl
---

## Introduction

Formal research proposals are a very important aspect of professional life, both within and beyond academia. They are the central means through which one obtains approval to do a research study at a University, as well as to obtain funding or the support and approval of stakeholders with an interest in research being proposed. Despite this, there are very few simple guides to the fundamentals of writing proposals, particularly in the Australian heritage sector: broadly, history, archaeology and cultural heritage in Australia. Hence, this guide is designed to aid students in these fields, and the humanities more generally, who need to prepare a research proposal for study with the author. These kinds of documents are first encountered by students during their degrees, often in advance of starting a dissertation-scale project, such as an Honours, Masters or PhD project. They are also important for smaller-scale research proposals, such as those required for undergraduate and postgraduate special topic, reading, or research units at UNE (e.g. HASS301, HASS505, and HASS506), as well as research projects completed as a component of a coursework Masters (HASS518).

## The context of research

Good research takes time, and lots of it, and should be carefully designed and thought through before it is attempted[@burkeDesigningYourProject2017]. This ensures a clear focus in your work, as well as a solid rationale for doing so; why do a research study if others have already done something similar? There can be good reasons for repeating a study, but as most research requires resources, including the time of people such as you, your supervisors, and other stakeholders, as well as funding or other material needs, it is important you consider the need for research before commencing. Research can also pose risks, most notably, the risk of causing harm to human participants in your research.

Research is not solely an academic pursuit. Heritage professionals, community development professionals, planners and many others will write 'research proposals' whenever they apply for a grant for funding or other resources to support a new project. Because cash and resources are generally finite and hard to obtain, formal proposals help decision-makers to choose which projects can be supported. Hence, if you can write a strong research proposal you will be better able to attract funding to support your work.

The University sector is usually where you learn to write a research proposal. Indeed, academic departments are where a majority of scholarly research proposals are written because of the flow of graduates into higher studies, such as Honours and Doctoral programs. When academic departments are considering accepting a new student researcher at this higher level, they are usually doing so in a context where there are limited resources. Most academic departments have insufficient staff to supervise all proposed projects, as well as a lack of available workload, physical space, or internal funding. Furthermore, not all project ideas or those proposing them are at a standard that they will be accepted. As such, the proposal serves to help others to consider your case for doing your research project, and to clearly demonstrate that you have a clear idea of what they will research and how they will do it *before* they are accepted into a program. If the proposal is weak, lacks detail or care, or simply untenable then it is likely the response from those you approach will be either a 'no' or simply ignored.

## Topic selection

Deciding what research topic you should focus on can sometimes be difficult. Some students have a very clear idea about what they would like to do, while others may only have a general feeling. It is best to meet with a potential supervisor only *after* you have made some initial decisions about your research topic, namely:

- What sub-discipline would you like to work in, and where do you see most opportunities? Historical archaeology? Critical heritage studies? Indigenous history? Figure that out first.

- Is there a particular area of research within that sub-discipline that interests you? Do not set out to research a topic that does not 'do it' for you! If you do not have a clear project, feel free to write to specialists who may have a topic in mind, waiting for the right student.

- Are there theoretical approaches that you would like to explore further? This is especially important in larger-scale projects where extensive engagement with current or historical theoretical debates is mandatory.

- Are there methods that you want to use? You may wish to learn or further develop and demonstrate a specialised methodology or analytical approach. Your proposal should absolutely be shaped to reflect and extend on your personal interests and goals.

There are of course many other considerations in choosing a topic. A key issue to keep in mind at this point is that all academic staff have long-standing areas of research interest, and these are clearly outlined on staff research pages. Look at the publications we author and the list of our current and past research projects. Can you see a staff member who you would like to work with and learn from? Are there staff working on questions and issues that interest you? In most academic proposals, this is vitally important to finding a supervisor and having your proposal accepted. You need to do some work here!

## Components of a viable topic

A core element of any research proposal is choosing a 'viable topic'. This is one of the more difficult tasks faced by novice researchers, particularly those coming into a Masters or Honours program, and where assistance will usually be required. What is 'viable' depends on the type of project you are proposing, and generally speaking you should take note of the following points:

### Time and scope

You need to be able to complete the research and write the thesis within the study period. There is no sense proposing to conduct a large program of research that will not be able to be completed within the time frame available to you. For smaller-scale projects, a trimester- or semester-long study might be all the time you have. For an Honours/Masters Coursework project, 8–10 months is more commonly available, while Master of Philosophy and Doctoral-scale projects extend over 2–4 years. Scale your proposal for the project in mind.

### Human research ethics approvals

There should be no insurmountable ethical reasons that the research should not go ahead. Ask yourself, will you be able to obtain permission to work on a collection, visit a study area, or to use the methods described? Is the topic of your research going to immediately raise concerns about ethics? Obtaining research ethics approval is certainly a surmountable task, and indeed, adds much value to the research conducted. In all cases, research proposals should explicitly address the question of whether an ethics approval will be required to conduct the research. If not, explain why. If you feel ethics is warranted, be sure to explain why you think it is necessary. Most studies that involve ethics include one or more of these components:

- undertaking interviews or questionnaires;

- using personal information, especially of people within living memory;

- conducting invasive, destructive or damaging work on cultural heritage sites, particularly Indigenous heritage places, objects or materials (this includes dating, sampling, excavation and anything destructive);

- studies that are upsetting, traumatic, or otherwise potentially cause emotional or physical harm to participants;

- using unpublished or otherwise not publicly available Indigenous heritage information (site records, oral histories, material culture collections);

- using cultural information that is restricted to a particular gender, cultural grouping, language group, cultural seniority, or community;

There are of course are many other examples of projects that will warrant an ethics approval. Such projects will almost always warrant both community approvals and at least a low-risk ethics approval process. You can find out more about UNE's ethics approval systems and resources [here](https://www.une.edu.au/research/research-services/research-ethics-integrity/human-research-ethics/hrechttps://www.une.edu.au/research/research-services/research-ethics-integrity/human-research-ethics/hrec).

### Resources

A good proposal will identify the resources needed to complete the research, and have good prospects of obtaining those. This might include having access to appropriate primary sources or physical samples, the right equipment, and in some cases, access to a stipend or other funding to support you while you undertake the research. If you need money to pay costs of volunteers, community participants, or field work costs, you need to say so and explain how you will cover that. You should always address resources and funding requirements very clearly in your proposal, and make it clear what resources are needed and how you will get them. Most proposals benefit by including a table summarising the financial and non-financial resources required. Make it easy for your reviewers!

### Supervision

Some of the fastest 'no' responses to supervision requests I write are those unsolicitied requests for supervision of project outside of my field. For example, students who have approach me about studies of Viking burials and Celtic symbolism, architecture in colonial India, or colonial European history of a suburb I've never heard of. My colleagues at two Australian universities have over the years often shared similar experiences. None of these projects are ever accepted because they are simply too marginal to our skills and expertise. No is the only answer we can reply with.

Your project will need to be supervised if undertaken at a University. You will need a 'yes' response from a potential supervisor, or at least a 'maybe'. Your proposal will be rejected if staff members feel that they are unable to adequately supervise it. Few, if any, academic departments in history or archaeology in Australia have sufficient staff to cover all sub-fields and specialisations available.

Students keen on putting forward a proposal should in the first instance be sure that their project is within a sub-field or research area that available staff can supervise. If you're not sure, ask, but in the first instance take a detailed look at relevant staff pages. Do the work. If those people do not exist at your current institution, or one you have close ties with, you may need to look elsewhere.

### Understand what is expected

It is important that you take some time to read a dissertation in your study area and at the scale you are expected to write well before you write a proposal. This will help you to understand the scale or scope of research required at different levels, and in turn help you with revising and refining your own proposal. This is also important if you are not sure just what these kinds of projects involve – for example, do not apply for a PhD position unless you really do want to spend 3+ years of your life studying, and you are absolutely excited about the topic. If you have questions about the requirements of these degrees, talk to key staff or a Higher Degree by Research (HDR) Coordinator, or to students who are currently working on a dissertation. Current students provide the best window in on life as a research student at your preferred institution.

## What is a research proposal?

The purpose of a research proposal is just as it sounds – to guide the research. In it, the purposes of the research are formally enunciated and the course it will take is laid out. Writing a proposal clarifies thought by determining specifically what questions will be addressed and how they will best be answered. It therefore facilitates the creation of data by determining exactly what will be considered data for the purposes of answering the questions posed, and how these data will be analysed. The research design should also highlight a central problem that the question relates to [@boothCraftResearch2019]. Essentially, the research design presented in the research proposal makes explicit the assumptions and informal plans of the researcher.

You may not know all the answers, or methods and approaches you will eventually use, but you should outline how you see things coming together now, and do some research to guide that understanding before you submit. The proposal is written early in the research process to help you and a supervisor to plan or guide the work. It is an initial phase in the work and there are certain things that it cannot and is not expected to do. Firstly, it is not 'written in stone' and no-one expects that the final research project will exactly reflect the plans laid out in a proposal. It is a plan of what you intend to do without actually doing it. To do otherwise would be both impossible and undesirable given the unexpected circumstances that inevitably arise during research and given the importance of remaining open to new or contradictory findings. This being said, it is expected that the proposal will continue to hold some relevance to the project and the research will not digress too far from the original plan. Consider the research design in your proposal a broad set of parameters to guide the work.

Secondly, it is not expected that the proposal will hold 'answers' to the questions posed. If it does, the project itself would be pointless. If 'answers' are known before the research is done, then the questions are probably too simplistic and more challenging ones need to be asked. All research should aim to generate new knowledge about a particular issue or *problem*. Often, your research problem will have multiple dimensions. For instance, you might be addressing a local or regional gap in terms of knowledge but, through your case study, you are developing an internationally relevant theoretical framework in interesting and important new ways. So, in this case, your project would be of local and international significance. You need to do your best to spell this out to the reader. Who cares about your study? Why?

In order to pose reasonable questions and probable outcomes, it is necessary to have some idea of what you want to research and why. For this reason the thesis proposal is going to be the very first stage of the project. Before writing the formal proposal it is necessary to decide why the project is to be done and what areas are of interest. It is also necessary to do quite a lot of reading in the general area of interest. If the topic has already been investigated, as is often the case, this will involve initial research into the history and background, and any previous work done. This will help you to more accurately outline an actual problem.

To learn more about defining research problems, and the differences and similarities between practical or applied problems on the one hand, and scholarly or academic problems on the other, see @boothCraftResearch2019. These authors provide an excellent overview and you should read at least the first four chapters, if not the entire book!

## Why is a proposal necessary?

A research proposal is one of the most important parts of your research journey and should be taken seriously. As noted above, in academic settings your proposal needs to compell one or more people of the merits of your proposed study to generate a 'yes' or 'maybe' response to your inquiry. This ranges from winning the support of one supervisor who you will, ideally, work with closely for the duration of your study, to passing a more formal review of a panel of scholars. This is commonly the case when you are applying for a scholarship or funding. In all cases, the proposal needs to make clear that you have the required knowledge, skills and experience to do the proposed work. It can also be an opportunity for you to obtain robust feedback on the proposal, hopefully with an invitation to resubmit if work is needed to improve on it. In doing this, reviewers who see value in yoru proposal will generally aim to be supportive and helpful, and will outline ways to improve the quality of your proposal rather than merely criticising or rejecting it.

Importantly, some proposals are rejected, and here are some common reasons for that. These include proposals that:

- are written by a chatbot 'AI' and are not your work. We can tell. Don't do it;

- are on a topic that does not align with the expertise of the supervisor, research group, or department you are applying to;

- are infeasible because of ethical, financial, technical, safety or other concerns you have not addressed;

- are 'thin', lacking sufficient detail in areas that matter; and finally,

- lack references, or do not illustrate even basic knowledge of the literature.

If the proposal has merit but needs work, these things will be pointed out to you. If the proposal is very poor quality, you might not even hear a response beyond the imaginary sounds of your email hitting a virtual rubbish bin. Academics are busy, and have plenty of great projects of our own to work on – we have already finished multiple theses ourselves, and many other foirmal studies, so you need to convince us you have done the work and have a great project idea!

There are benefits of going through the process of writing a proposal, and submitting your work to a wider audience:

- The prospect of having to perform in front of a critical audience does seem to galvanise most people into action. Hypotheses and research questions become sharper, the methods are explored in greater depth, and the validity and reliability of the study are considered.

- Many readers have probably had some experience of what you are proposing, and will often come up with suggestions that will improve your proposal. Listen to those, even if you think they are stupid and you already have all the answers (and you do not). Equally, the criticisms and comments that they make can be noted and addressed in the research itself. It can be a valuable exercise to use the proposal process to vent a problem or issue that you are grappling with, and obtain the thoughts of your audience.

- The proposal helps you identify problems early in the research process and establish whether your project is feasible, as noted. You can build on negative feedback, learn from it, improve the work. This is not a point to give up.

- The proposal document can be used as a basis for a final thesis or write-up. Some academics claim that a good proposal can form Chapter One of a first dissertation draft. While this may not always be the case, a robust proposal is certainly an early down payment on getting those all-important background and methods chapters conceptualised, if not drafted to a basic level. It also helps you to think through what your thesis will look like, and what you do need to do, and when.

- The proposal gives the impetus to create timelines, milestones and contingencies, which will help to keep you on track. Use these as a basis for managing your time, your energy, your wellbeing, and your inexorable progress towards your deadline.

## How long should a proposal document be?

Very simply put: as long as the relevant guidelines require!

The length of the proposal varies depending on the degree or unit level. For example, PhD candidates submit two different proposals: the first for admission, and the second for [confirmation of candidature](https://www.une.edu.au/research/graduate-research-school/current-students/confirmation-of-candidature) (at the first-year review point).

Word counts listed below [exclude]{.underline} references and any tables, figures, or appendices, and are intended to provide a general guide only:

- UNE Special Topic / Reading / Research Units (HASS301, HASS505, HASS506): 500–750 words;

- Honours and Coursework Masters applicants: 500–2,000 words;

- Masters by Research: 1,500–3,000 words;

- PhD application for admission: 2,000–4,000 words.

For students enrolling in undergraduate or postgraduate special topic, reading, or research units at UNE (such as HASS301, HASS505, or HASS506), consult the [UNE HASS Special Topic, Reading and Research Units guide](https://www.une.edu.au/about-une/faculty-of-humanities-arts-social-sciences-and-education/hass/current-students/hass-special-topic-reading-and-research-units). For these units, a concise 500–750 word proposal serves as a formal learning and research agreement between you and your supervisor. It confirms the proposed scope, reading schedule, assessment structure, and feasibility, as well as establishing whether any human research ethics approvals will be required prior to enrolment approval.

A word of advice: Do not start off on the wrong foot with the academic panel or your supervisor by submitting a document that is too long or too short (i.e. \> ±10%). The word limits are there for a reason – to help evaluate your writing ability and your capacity to define a feasible research project concisely. If you go over or are too brief, your application will run the risk of being returned for revision or ruled out entirely.

## What should be included?

A key question to remember when planning your proposal is: why you are doing the research in the first place? A major requirement of any research is that the proposed study makes an original contribution to knowledge. It might be a small contribution, but a contribution it must make!

During the examination process, once a thesis is written, students must demonstrate that they have carried out significant, critical research and have produced an original body of work or critically synthesised existing knowledge into a new and meaningful way so as to become a useful contribution to existing scholarship. It is difficult to do that if your topic is well researched and published already. What is different about your study?

Thus, the most important thing is that your proposal should explain a broad problem or gap in existing scholarship and then outline what you will do to address it: what will *your* contribution be? You will be unlikely to change the discipline, your field of research or even reshape debate on a topic, but you can add to it, raise new questions or bring new data and insights, theories or understandings, to build on the work of others.

Organisation is critical, especially in the beginning of your research. How you organise your research will determine how your reader interprets your ideas. As an indicative format, your thesis propsoal should include:

### 1. Cover page

This should include a title, your name and the names of your nominated supervisors where these have been identified. List any prior qualifications you have (mainly degrees, and qualifications relevant to the topic being proposed).

The project title is usually a difficult thing, and there is no requirement to make it anything other than a clear statement of what the project is about. What your final dissertation or report title will be is another matter, something you will worry about in future, so at this stage ensure your title communicates clearly what the project will be about. Avoid alienating the reader with jargon or other words not commonly used in your field. It will just annoy someone!

### 2. Introduction

This is a broad synopsis of the proposal. Read @boothCraftResearch2019 on how to develop a thesis statement, and write one. Use that to start the proposal as this is exactly the kind of clear, snappy, all-encompassing formal statement summarising the research project. This should include giving the reader a sense of your specific question, your wider problem, and the significance of this study at this time. It is also good to note what the project involves, its timeline, study area and any other major issues that emerge in your proposal.

An introduction in the order of 100-300 words long is recommended.

### 3. Research design

This is undoubtedly the more difficult aspect of a research proposal, and outlined here in detail. Start the research design with a clear statement of your problem and topic, but try to paraphrase this differently to the introduction to the proposal.

Start the proposal by outlining a central problem. This will be based on a literature review and so it is the case that the first major part of the proposal you write should be the literature review. That should be usually the largest part of a research proposal. Take your time, read widely, and present a solid, well referenced account of previous research and, in that, identify what the problem is. There are many great guides to writing a literature review (see Section 4, Literature review).

Once you have completed the literature review, you should be able to concisely write a paragraph that outlines the research problem. When you have done that, you are ready to write a research design. See @burkeDesigningYourProject2017 for more information on this.

#### 3a. Research questions

Identify a central question or several questions that your thesis will investigate. This should be phrased as a question, not as a statement. Do not list out a series of loosely-related questions or 'quasi-questions' that often resemble unformed ideas. Rather than impressing the reader with your many ideas, this is more likely to send the message that the research question at the heart of the project is unfocused and unclear, and needs refinement. While Doctoral and Masters by Research proposals might often include 2-3 carefully articulated questions, projects with a smaller scope will usually require only one question.

One approach to doing this is to create a 'question bank' (a list of possible questions in your notes) as you make your way through your long reading list. This is a really important step in developing a question, but requires a further step of 'winnowing' and revising your potential list of questions to something more focused and specific. Mind-maps are a great way to do this, particularly for those of us who like to think visually. Do it with a computer or a large sheet of paper, the outcome will hopefully be the same: a clear, focused question.

The research question should clearly outline how you will address the problem. It will not be the only way, or even the best way to address the problem, but that link should be made clear.

#### 3b. Research aims

The best way to think about research aims is that they are your 'to do' list for your project. That is, they should ideally spell out what research you need 'to do' to answer the question. What do you need to achieve to enable you, in your final discussion, to consider and make a case addressing your central question?

Importantly, these are not statements about your methods, but are more about what you need to achieve through the research to answer your question. For example, a historical research question about social life and experiences of new Irish immigrants on a 19th century goldfield may well have objectives such as:

- Characterise the pattern, pace and context for establishment of new goldfields in the study area at the time, both in relation to local and global forces and processes;

- Explore and thematically analyse historical scholarship on the Irish diaspora in Australia;

- Document popular attitudes to Irish and other immigrants on north Queensland goldfields, from the mid-1800s onwards;

- Identify and complete life-histories of prominent Irish people and families working across goldfields in the study area at the time, and;

- Characterise the extent and nature of interaction between Irish people through analysis of letter books and other primary sources.

Now these are not necessarily good or even feasible 'aims'; just examples to help you think. But, looking at them, can you see how each will help to generate a particular body of work? For aim 1, the researcher might review literature on gold mining in the late colonial period (\>1850s). Aims 2 and 3 would require more focused research into secondary sources for the study area ('north Queensland'). Achieving the final two aims would warrant more intensive work on primary sources. An archaeological or cultural heritage study might include more detail on collecting spatial data on Irish settlements, or analysing symbolic motifs on headstones of those born in Ireland in a local cemetery.

#### 3c. Methodology

These should clearly explain what methods you will adopt to address your aims and answer your research question/s. These need to be detailed rather than brief or generic statements. Spell out the specifics of what you plan to do.

Methodology should ultimately aim to outline aspects of:

- Your research strategy. Will you be using qualitative or quantitative data? How do you propose to use these data? What is your broader approach to integrating various lines of evidence together to help address your question?

- Theoretical frameworks? Is there a particular theory you wish to explore through your work? What assumptions are you working through in undertaking this study? Theory can also take a more central role, for instance, in the definition of the problem or the framing of the study from the outset.

- What particular methods will you use? This covers both the steps in creating (or collecting) data, as well as how you will embark on your analysis.

- Where is the case study or context for your work?

- What are the possible limitations and constraints, as well as any other issues that might impact on the feasibility of the project? Don't complain that you need lots of money, but do highlight things that might get in the way; e.g. archive access, finding appropriate primary sources; having access to collections; and so on. If you are using data created by others, it is a fact that you cannot control the way others have created their data—so your project will potentially be constrained by that.

Historians will often be less concerned with methods and techniques than with framing how they will approach the analysis at a more conceptual level (e.g. 'Here I use Foucault's theory of 'governmentality' to explore XYZ', and going on to explain this in detail). Archaeological methodologies tend to be oriented toward this as well as a range of discrete methods (radiocarbon dating, PXRF analysis, geochemistry, fauna analysis, spatial analysis, etc). Of course, both disciplines involve work that is different to these stereotypical approaches, and for example, historians will make considerable use of a range of quite specific methods. One common example increasingly is their use of sophisticated computational methods to analyse massive text corpora. Similarly, many archaeologists love to delve into a large collection of primary sources for fragments of information to help unpack the story of a particular place, building or community in the past. It is for these reasons the differences between history and archaeology are more imagined than real, and students certainly stand to benefit from learning about methodology across different disciplines. Do not restrict your thinking to a perceived disciplinary silo!

Before attempting to write up your methods, be sure to look for examples in your particular field of study. A recent completed thesis is a great place to read about methodology! Often, lots of detail about methodology is stripped out of publications and so these are not always as useful as a thesis for learning about methods. The best place to start is the UNE library's [RUNE (Research \@ UNE) repository](https://rune.une.edu.au/web/handle/1959.11/26187). [Trove](https://trove.nla.gov.au/search/advanced/category/research?l-advformat=Thesis) has a capacity to search theses also (select 'Research Reports' and 'thesis' from the search options).

#### 3d. Project rationale

A discussion of the key reasons that this project is significant in relation to the literature. E.g. are you applying a new theoretical framework or research method to a long-standing problem? Will you generate new data that provides a completely new perspective on the research problem? What is the significance of your study? Why do we need to do this research now, or even at all? The other dimension of this is relevance to a stakeholder; for instance, a project might be requested by a community organisation to address a need or problem. This is important, so tell us!

#### 3e. Collaboration, community and stakeholder engagement, and human research ethics

There is very little research that happens entirely in isolation, separated from the need to collaborate, consult or consider human research ethics. Indeed, all researchers have a responsibility to address ethical matters pertaining to their research well in advance of undertaking that research. It is for this reason you should include a heading on collaboration, consultation and ethics in your proposal—so that you can, even briefly, reassure the reader that you are on top of these issues.

Collaboration requires a statement about the wider context of the research. Many students increasingly take on research projects as part of larger, longer-term studies, so in these situations you would outline that wider context and support network you are enmeshed with. Collaboration might also be with community members or organisations supporting your work, or indeed the actual participants you wish to work with. This does not need to be a detailed section, but be sure to explain what the wider context is for your study. If there are funding arrangements in place set up by others before your involvement in the study, note them here. This is important.

Similarly, community and stakeholder engagement reflects the fact that often we need to discuss our work with others at various points, or to seek formal approvals. This should definitely be canvassed at the start of any project. Who might you need to talk to? Why? Are there approvals required? Do you need to report on your work, or provide a copy of outcomes of your research once completed (e.g. a poster, publication or report). Tell the reviewers. This might be a property owner, local Aboriginal land council, local council or manager of the archive you intend to work in.

If you need to apply for ethics permission through the university, you need to do this early, but not before you are enrolled. You can read more about [Human Research Ethics at UNE on the relevant webpage.](https://www.une.edu.au/research/research-ethics-integrity/human-research-ethics) A project that involves exploration of an aspect of [Indigenous Cultural and Intellectual Property](https://www.artslaw.com.au/information-sheet/indigenous-cultural-intellectual-property-icip-aitb/) will almost always require ethics approval. See also the AIATSIS guidelines [@aiatsisAIATSISCodeEthics2020].

### 4. Literature review

This comprises a literature review that identifies a broad research problem (or series of research problems) that you will set out to address. The focus is largely to explain the literature and to identify problems, gaps, key findings and insights, theories, debates and so on. This should represent at least 30-50% of your proposal, in terms of word count and effort. There are many guides to writing a thesis, and these all generally include commentary on how to write a literature review [e.g. @barzunModernResearcher2004; @billmcdowellHistoricalResearchGuide2013; @bolkerWritingYourDissertation1998; @boothCraftResearch2019; @boothSystematicApproachesSuccessful2012; @burkeDesigningYourProject2017; @connahWritingArchaeology2010; @ecoHowWriteThesis2015; @faganWritingArchaeologyTelling2006; @hayotElementsAcademicStyle2014; @murrayHowWriteThesis2017].

### 5. Timeline and resources

Provide a summary of the major milestones in your research and an indication of what resources are required for each stage. Noting any resource issues is particularly important for thesis projects involving fieldwork, travel or specialised analytical procedures. If you are happy to 'self-fund' some expenses, then certainly say so. If you are applying for a PhD position, you are likely to be able to access funding to support your work—so find out about that and ensure your budget is within scope. If not, identify what grants you will apply for and when. List that out to show you have thought this through!

### 6. References

Follow your discipline here, and for proposals at UNE, use either History Footnoting or APA7. Despite being a common question asked by students, there is no 'fixed number' of references to cite, but certainly you should have 1-2 pages in most cases, and possibly more.

Do use a reference manager to help manage your sources. I strongly recommend <https://zotero.org> over EndNote or other paid-for tools, since it is a resource you will develop and use as long as you need into the future.

## Do I need to find a supervisor?

**Yes**, but ensure you have done some homework first.

The role of an academic supervisor is broadly to support and guide the development of your thesis. Because a thesis begins with your proposal, it follows that you should begin to think about an appropriate supervisor very early in the development of a proposal. This is to ensure that you develop a proposal that falls within an area of expertise of at least one staff member. If your proposal does not fit this broad prerequisite, then it is possible that your proposal will be rejected outright—or at least you will be asked to complete a major rewrite and to identify a new topic. The second reason to find a potential supervisor early is because they will, hopefully, be able to read your proposal draft and provide feedback to help improve it, but only if you give them enough time to comment. If you find yourself with a supervisor who is friendly, responsive and supportive as well as being a leader in their field, and who reads things and provides useful comments, then you are off to a good start!

A good proposal should be developed with a specific supervisor in mind. So, if you have an idea for a project, take some time to review the websites of Academic Staff to identify individuals with broad expertise in your research area. Once you find a potential supervisor, take the time to **read relevant publications they have authored** while you are conducting your literature review. Look into the kinds of topics they teach and the research projects they are involved in. In some cases, staff members have very specific projects in mind for future students or will be only open to supervising projects within a very specific research area. Whatever the case, it is advisable to make contact with a potential supervisor very early in the development of your proposal, ideally two months before your proposal is due. This provides ample opportunity to develop a proposal that is tightly integrated with current research being conducted, and more importantly, that is of interest and relevance to your supervisor. This will help to ensure that the proposal you develop is a good match for the supervisor/s and will result in a stronger project and high quality outcomes. Again, this speaks to feasibility.

If you are unsure what a supervisor does then take time to read the [University's guidelines on the roles of supervisors](https://www.une.edu.au/research/graduate-research-school/current-students/supervision-agreement-between-students-and-supervisors).

## General tips

These are offered for those of you who might be thinking about doing an Honours, Masters or PhD project at some point in the near- to medium-term.

- **Are you ready?** Think very seriously about whether you can commit to a research thesis before you apply. An Honours or Coursework Masters thesis will take you at least six to eight months of sustained full-time research, if not longer. A PhD thesis will take you at least three years full time, and most students take closer to four years full time. Can you focus on a research project for this length of time? Are you up to the task of writing a thesis? It is a big decision, and good to discuss with family, friends or academic mentors.

- **Take note of word limits**. They are there for a reason: to show that you can present a clear account of your proposed research in a concise way. Do not give the person/people reviewing your proposal a reason to doubt you.

- **Write a strong literature review**. Make sure your 'research problem' is backed up with a first-class literature review and careful in-text referencing/footnotes. That is, try and impress the reader by showing evidence that you have worked hard to identify a problem that is of wide significance and that you have a scholarly approach to research. While your opinion and arguments do matter, we also need to see that you are aware of what other researchers have said about the topic at hand. It is usually the case that a weak proposal is weak because the author has limited knowledge of the extant literature, and fills the proposal with unsupported claims about a major problem that they haven't bothered to properly research. That is, they have not read enough, or widely enough, to be able to say anything meaningful about their research problem, question or its significance.

- **Do not submit 'surprise' proposals**. If you are submitting a research proposal for a formal position in, say, an Honours or PhD program, then be sure that you have discussed your thesis ideas with a potential supervisor, as noted earlier, at least a couple of months in advance. If you are unsure who to approach, find out. When you do approach a potential supervisor, provide a half page summary of your central topic and approach, so that they can (hopefully) give you some broad advice before you do the work required for a fully formed proposal. This will help to ensure that your proposal is more likely to be accepted by the potential supervisor, and that it is a feasible proposal in line with the research expertise of the Department you hope to enter!

- **Finally, do not rely on AI**. Do your literature review the hard way (search [Google Scholar](https://scholar.google.com), [OpenAlex.org,](https://openalex.org) your library databases, and so on, *thoroughly*); read the papers and book chapters, summarise the key points yourself. Don't ever rely on AI generated slop. AI doesn't have a brain like you do, and the point of study is to learn, to improve your understanding and knowledge. If your proposal is based on AI slop, your professionalism will be immediately questioned since an astute supervisor will likely see through it in a second and ignore your proposal as a result. Show us you are a human with a human brain who wants to learn and who can think.

Good luck!

Mick Morrison

\(c\) 2025

## Acknowledgements

This has been developed based on teaching research design and proposal writing in two Australian universities, UNE and Flinders. It includes and indeed has significantly benefited from ideas, experience and time in the trenches teaching with colleagues including Professor Heather Burke, Professor Claire Smith, Professor Lynley Wallis and Professor Wendy van Duivenvorde. The document is authored by Mick Morrison and has been developed since 2017.

## References
